Player Profile - VERSION 2.0
danielkboyer/box-heads pull request #13
Opened 2022-11-13 06:48 UTC by Maphesdus

2022-11-13 18:47 UTC, ktwitchn reviewed
A good starting place for me to use in the vote page.

2022-11-13 18:47 UTC, ktwitchn commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +}
Same as the class above, also use variables for colors

2022-11-13 18:47 UTC, ktwitchn commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +    </div>
Should we wrap this in a flex container?

2022-11-13 18:47 UTC, ktwitchn commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +        src="/images/player_profile_images/LebronPost.png"
Add a prop on src so I can pass in different images based on which player I'm displaying

2022-11-13 22:57 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +        src="/images/player_profile_images/LebronPost.png"
Add a prop on src? What does that mean?

2022-11-14 01:53 UTC, ktwitchn commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +        src="/images/player_profile_images/LebronPost.png"
Sorry I should have said that better. Basically create a property for this component that allows me to update the src when I use the tag:

<playerProfile src="example.png"><playerProfile>

boxheadsButton does a similar thing with title, navigation link, etc.

2022-11-14 02:53 UTC, danielkboyer commented
It's hard for me to review this because the result doesn't look like the figma result. This needs more work before it can be reviewed properly. 
<img width="148" alt="Screenshot_20221113_075045" src="https://user-images.githubusercontent.com/23005015/201565152-56851a0a-e425-4880-aaf5-974ab68e9346.png">
<img width="167" alt="Screenshot_20221113_074946" src="https://user-images.githubusercontent.com/23005015/201565154-1db681b5-97cc-421b-9947-c7934825f67e.png">

2022-11-14 02:58 UTC, danielkboyer requested changes
Needs more work. Check comment above.

2022-11-14 05:20 UTC, Maphesdus commented
> 

Thank you. I'll fix it tomorrow.

2022-11-15 22:56 UTC, closed without merging