Created player profile component and added player images
danielkboyer/box-heads pull request #7
Opened 2022-10-12 00:58 UTC by Maphesdus

2022-10-12 01:27 UTC, danielkboyer requested changes

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +import Image from 'next/image'
NIT:Name this file and the css file playerprofile

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +				<BoxheadsButton title='vote' onClick={()=>{}} className="actionClick"></BoxheadsButton>
className needs to be {buttonStyles.actionClick} and you need to import button styles

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +    font-weight: 700;
font weight should be 500 not 700

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +    font-size: 24px;
font size should be 10px according to figma, and line height should be 11

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +.teamName {
Team name doesn't match the figma mocks, it needs to be smaller and greyed out

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +				<input type="text" placeholder="Notify by email" />
The input doesn't look like the mocks input

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +			<label className={styles.teamName}>TEAM</label>
I would replace these with the boxheads label once you're finished and update this PR afterwards

2022-10-12 01:27 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +			<label className={styles.playerName}>PLAYER NAME</label>
There needs to be a space between the player name and number

2022-10-19 00:06 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +.player {
That's bad practice. File names should always have some way to determine where one word ends and another begins. Whether that be capital letters, and underscore, or a hyphen, there needs to be something to distinguish words from each other.

2022-10-19 00:22 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +			<label className={styles.playerName}>PLAYER NAME</label>
This will be addressed in the label component by adding padding to the CSS style sheet.

2022-10-19 00:28 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +				<BoxheadsButton title='vote' onClick={()=>{}} className="actionClick"></BoxheadsButton>
Done.

2022-10-19 00:28 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +    font-weight: 700;
Done.

2022-10-19 00:29 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +    font-size: 24px;
Done.

2022-10-19 00:30 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +.teamName {
Done.

2022-10-19 00:30 UTC, Maphesdus commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +			<label className={styles.teamName}>TEAM</label>
Will do.

2022-10-19 21:03 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.module.css
> +.player {
I understand what you're saying, inside of `playerprofile.tsx`  the class is kebab case `PlayerProfile`, the main reason I did all lower case is because that's what my work does for angular files (react.js is very similar). I don't think it's that unreadable and prefer how it looks, after doing a quick internet search it looks like it's up to the developer and their preference. Since all the files are already lower case I say we stick to that.

2022-10-19 21:09 UTC, danielkboyer commented on website/boxheadsweb/components/playerprofile/playerProfile.tsx
> +				<BoxheadsButton title='vote' onClick={()=>{}} className="actionClick"></BoxheadsButton>
Just curious, when you say done does that mean you pushed those changes? or they are only on your local computer.

2022-10-25 20:24 UTC, Maphesdus commented
Updated Player Profile CSS

2022-11-14 04:49 UTC, closed without merging